### ISSUE TITLE
Створення layout'а для сайту

### ISSUE THREAD

**Issue by Xobb** [DigitalPolice/citydepartment#11]
Я попередньо включив MopaBootstrapBundle і Assetic, потрібно зробити layout.html.twig з відповідними джаваскриптами, стилями і рештою, на основі якого буде розроблятись інтерфейс.

**Comment by ipetrovych** [comment]
Думаю можна взяти шось типу http://blackrockdigital.github.io/startbootstrap-scrolling-nav/ за основу

**Comment by Xobb** [comment]
#13 вмерджено.
