### ISSUE TITLE
Створеня Doctrine 2 Entity

### ISSUE THREAD

**Issue by Xobb** [DigitalPolice/citydepartment#2]
Потрібно створити Entity для роботи з даними. Список ентіті з полями:

1. Point [Single Table Inheritance](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance)
2. Crime (extends Point)
3. Camera (extends Point)
2. Crime Type
3. User
4. Poligon (entity)
5. Organisation [Single Table Inheritace](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance)
6. Headquaters (extends Organisation відповідає Управлінню)
7. Department (extends Organisation відповідає відділеню)
8. District (extends Organisation відповідає дільниці)
9. District Officer (extends Organisation відповідає дільниці)

Тепер по атрибутам і зв'язкам між сутностями.

### Point

1. address (string 255)
2. longitude (float 10,6)
3. latitude (float 10,6)
2. created_at (використай [DoctrineExtension Timestampable](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/timestampable.md))
3. updated_at (так само)

### Crime 

В силу того що ми йдемо наслідуємось від точки, то всі атрибути точки залишаються плюс:

1. description (text)
3. reporter_id [ManyToOne Unidirectional](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#many-to-one-unidirectional) to User
4. crime_type [ManyToOne Unidirectional](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#many-to-one-unidirectional) to CrimeType

### Camera

1. description (text)
2. stream_url (text)

### CrimeType

Сама проста таблиця

1. title (string 255)
2. icon (string 255)

### User

За основу беремо FOSUserBundle. Додаємо поле:

1. phone_number (integer)

### Poligon

1. points [ManyToMant unidirectional](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#many-to-many-unidirectional)

### Organisation 

1. title (string 255)
2. address (string 255)
6. schedule (text)
3. parent [OneToMany Self referencing](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#one-to-many-self-referencing) to Organisation
4. headquaters [OneToOne Unidirectional](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#one-to-one-unidirectional) to Point
5. area [OneToOne Unidirectional](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#one-to-one-unidirectional) to Poligon

**Comment by ipetrovych** [comment]
Finished entities
