### ISSUE TITLE
Аутентифікація і авторизація

### ISSUE THREAD

**Issue by Xobb** [DigitalPolice/citydepartment#5]
Потрібно зробити форму аутентифікації і розкласти вимоги авторизації.

Будуть наступні ролі:

IS_AUTHENTICATED_ANONYMOUSLY: можливість переглядати злочини на карті
ROLE_USER: можливість залишити заявку про злочин.
ROLE_ADMIN: редагування Organisations і користувачів.

**Comment by ipetrovych** [comment]
Will need to play around with layout later, but for now it's done.

**Comment by ipetrovych** [comment]
@rommelnyk, Поки зробив простий логін-пароль. Як буде sms gateway - то можу зробити через телефон логін. Але тоді шукай де, як і за скільки.

**Comment by Xobb** [comment]
Я думаю що цю ісью можна закрити та відкрити нову доя смс аутентифікації для користувачів. А адміністратори і так будуть ходити через фаєрвол з емейлом і парольом.
